### ISSUE TITLE
Cell C25 causes crashes

### ISSUE THREAD

**Issue by AndyClifton** [IEA-Wind-Task-32/wind-lidar-ontology#15]
Entries in cell C25 cause the sheet2RDF processor to crash. See e.g. https://github.com/IEA-Wind-Task-32/wind-lidar-ontology/actions/runs/857357051.

@niva83 try putting a value in https://docs.google.com/spreadsheets/d/1rC2bugsJzRpuINqbVKR7GO1xNHPvzUvrKEz-75MNdXY/edit#gid=1744776504&range=C25.

... and then running it.

**Comment by niva83** [comment]
This is not due to values you put in cell, but you probably have one too many opened Sheets.
Try hitting 'Ctrl+S' and close the sheet (tab in which it is opened) and re-try triggering the pipeline.
